# This is the default configuration file
postgresql:
  host: localhost
  name: pyazo
  user: pyazo
  password: 'env://POSTGRES_PASSWORD'

redis:
  host: localhost
  password: ''
  cache_db: 0
  message_queue_db: 1

debug: false

# Error reporting, sends stacktrace to sentry.beryju.org
error_reporting: false

domain: localhost
