# This is the default configuration file
postgresql:
  host: localhost
  name: pyazo
  user: pyazo
  password: 'env://POSTGRES_PASSWORD'

redis:
  host: localhost
  password: ''
  cache_db: 0
  message_queue_db: 1

debug: false

# Error reporting, sends stacktrace to sentry.beryju.org
error_reporting: false

# Set this to the server's external address.
# This is used to generate external URLs
external_url: http://localhost

# This dictates how the Path is generated
# can be either of:
# - view_sha512_short
# - view_md5
# - view_sha256
# - view_sha512
default_return_view: view_sha256
