# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            options={
                'db_table': 'pyazo_upload',
            },
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, upload_to='')),
                ('type', models.IntegerField(choices=[(0, 'Picture')])),
                ('md5', models.CharField(blank=True, max_length=32)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('sha512', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            options={
                'db_table': 'pyazo_uploadview',
            },
            name='UplodaView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewee_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewee_dns', models.TextField(blank=True)),
                ('viewee_date', models.DateTimeField(auto_now_add=True)),
                ('viewee_user_agent', models.TextField(blank=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyazo_core.Upload')),
                ('viewee', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
