# Generated by Django 2.1.2 on 2018-10-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyazo_core', '0007_upload_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnail/'),
        ),
    ]
