# Generated by Django 2.1.2 on 2018-10-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyazo_core', '0008_upload_thumbmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='type',
        ),
    ]
