# Generated by Django 2.1.4 on 2018-12-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("pyazo_core", "0012_auto_20181117_1158"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="collection",
            table=None,
        ),
        migrations.AlterModelTable(
            name="upload",
            table=None,
        ),
        migrations.AlterModelTable(
            name="uploadview",
            table=None,
        ),
    ]
