# Generated by Django 3.0.3 on 2020-02-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pyazo_core", "0014_auto_20181221_1919"),
    ]

    operations = [
        migrations.RunSQL(
            (
                "UPDATE pyazo_core_object SET file = "
                "replace(file, '/usr/share/pyazo/media/', '/app/media/');"
            )
        ),
    ]
