# Generated by Django 3.0.3 on 2020-02-26 13:53

from django.db import migrations


def fix_file_path(apps, schema_editor):
    Object = apps.get_model("pyazo_core", "Object")
    db_alias = schema_editor.connection.alias
    for obj in Object.objects.using(db_alias).all():
        path = obj.file.path
        if path.startswith("/usr/share/pyazo/media/"):
            obj.file.path = path.replace("/usr/share/pyazo/media/", "/app/media/")
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pyazo_core", "0014_auto_20181221_1919"),
    ]

    operations = [
        migrations.RunPython(fix_file_path),
    ]
