---
version: '3.7'

services:
  postgresql:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - internal
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PYAZO_POSTGRESQL__PASSWORD}
      - POSTGRES_USER=pyazo
      - POSTGRES_DB=pyazo
    labels:
      - traefik.enable=false
  redis:
    image: redis
    networks:
      - internal
    labels:
      - traefik.enable=false
  server:
    image: beryju/pyazo:${SERVER_TAG:-latest}
    env_file:
      - .env
    environment:
      - PYAZO_REDIS__HOST=redis
      - PYAZO_POSTGRESQL__HOST=postgresql
    volumes:
      - ./media:/app/media
      - ./media/thumbnails:/app/media/thumbnails
    ports:
      - 8000:8000
    networks:
      - internal
  worker:
    image: beryju/pyazo:${SERVER_TAG:-latest}
    command:
      - ./manage.py
      - bootstrap
      - celery
      - worker
      - --autoscale=10,3
      - -E
      - -B
      - -A=pyazo.root.celery
      - -s=/tmp/celerybeat-schedule
    volumes:
      - ./media:/app/media
      - ./media/thumbnails:/app/media/thumbnails
    networks:
      - internal
    labels:
      - traefik.enable=false
    env_file:
      - .env
    environment:
      - PYAZO_REDIS__HOST=redis
      - PYAZO_POSTGRESQL__HOST=postgresql

networks:
  internal: {}
