---
version: '3.7'

services:
  postgresql:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - internal
    env_file:
      - .env
    environment:
      - POSTGRES_USER=pyazo
      - POSTGRES_DB=pyazo
  redis:
    image: redis
    networks:
      - internal
  server:
    image: beryju/pyazo:${SERVER_TAG:-2.2.0}
    env_file:
      - .env
    environment:
      - PYAZO_SECRET_KEY=${PYAZO_SECRET_KEY} # explicitly define this variable so theres a warning when its undefined
      - PYAZO_REDIS__HOST=redis
      - PYAZO_POSTGRESQL__HOST=postgresql
      - BOOTSTRAP_MODE=server
    volumes:
      - ./media:/app/media
    ports:
      - 8000:8000
    networks:
      - internal
  worker:
    image: beryju/pyazo:${SERVER_TAG:-2.2.0}
    env_file:
      - .env
    environment:
      - PYAZO_REDIS__HOST=redis
      - PYAZO_POSTGRESQL__HOST=postgresql
      - BOOTSTRAP_MODE=worker
    volumes:
      - ./media:/app/media
    networks:
      - internal

networks:
  internal: {}
