site_name: Pyazo Documentation
site_url: https://beryju.github.io/pyazo
copyright: "Copyright &copy; 2019 - 2020 BeryJu.org"

nav:
- Home: index.md
- Installation:
    - Package: install/package.md
    - Docker / Kubernetes: install/docker.md
- Configuration:
    - Initial Configuration: configuration/initial.md
    - Reverse Proxy: configuration/nginx_reverse_proxy.md
    - Migration between systems: configuration/migration_between_systems.md
    - LDAP: configuration/ldap.md
    - OIDC: configuration/oidc.md
- API:
    - Endpoints: api/api_endpoints.md

repo_name: "BeryJu/pyazo"
repo_url: https://github.com/BeryJu/pyazo
theme:
  name: "material"
  logo: "images/logo.png"

markdown_extensions:
  - toc:
      permalink: "¶"
  - admonition
