site_name: Pyazo Documentation
site_url: https://beryju.github.io/pyazo
copyright: "Copyright &copy; 2019 - 2020 BeryJu.org"

nav:
- Home: 'https://pyazo.beryju.org'
- Installation: install.md
- Configuration: configuration.md
- API: api.md
- Upgrading:
    - to 2.0.0: upgrading/to-2.0.0.md
    - to 2.1.0: upgrading/to-2.1.0.md
    - to 2.2.0: upgrading/to-2.2.0.md
    - to 2.3.0: upgrading/to-2.3.0.md

repo_name: "BeryJu/pyazo"
repo_url: https://github.com/BeryJu/pyazo
theme:
  name: "material"
  logo: "images/logo.png"

markdown_extensions:
  - toc:
      permalink: "¶"
  - admonition
