site_name: Pyazo Documentation
site_url: https://beryju.github.io/pyazo
copyright: "Copyright &copy; 2019 - 2020 BeryJu.org"

nav:
- Home: index.md
- Installation: install.md
- Configuration: configuration.md
- API: api.md

repo_name: "BeryJu/pyazo"
repo_url: https://github.com/BeryJu/pyazo
theme:
  name: "material"
  logo: "images/logo.png"

markdown_extensions:
  - toc:
      permalink: "¶"
  - admonition
