apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyazo.fullname" . }}-config
data:
  config.yml: |
    # Env for Docker images
    databases:
      default:
        engine: django.db.backends.postgresql
        name: {{ .Values.postgresql.postgresqlDatabase }}
        user: postgres
        password: {{ .Values.postgresql.postgresqlPassword }}
        host: {{ .Release.Name }}-postgresql
        port: ''
    log:
      level:
        console: DEBUG
        file: DEBUG
      file: /dev/null
    email:
      host: localhost
      port: 25
      user: ''
      password: ''
      use_tls: false
      use_ssl: false
      from: pyazo <pyazo@domain.tld>
    web:
      listen: 0.0.0.0
      port: 8000
      threads: 30
    debug: false
    redis: ":{{ .Values.redis.password }}@{{ .Release.Name }}-redis-master"
    # Error reporting, disabled by default
    error_report_enabled: {{ .Values.config.error_reporting }}

    # Set this to the server's external address.
    # This is used to generate external URLs
    external_url: {{ .Values.ingress.defaultHost }}

    # This dictates how the Path is generated
    # can be either of:
    # - view_sha512_short
    # - view_md5
    # - view_sha256
    # - view_sha512
    default_return_view: view_sha256

    # Set this to this server's hostname or the external domain if behind a reverse proxy
    domains: {{ .Values.ingress.hosts }}

    # Set this to true if you only want to use external authentication
    external_auth_only: false

    # If this is true, images are automatically claimed if the windows user exists
    # in django
    auto_claim_enabled: true

    # LDAP Authentication
    # ldap:
    #     enabled: false
    #     server:
    #         uri: 'ldap://dc1.example.com'
    #         tls: false
    #     bind:
    #         dn: ''
    #         password: ''
    #     search_base: ''
    #     filter: '(sAMAccountName=%(user)s)'
    #     require_group: ''

    {{- if .Values.config.secret_key }}
    secret_key: {{ .Values.config.secret_key }}
    {{- else }}
    secret_key: {{ randAlphaNum 50 }}
    {{- end }}
