#!/bin/sh
# config maintainer script for pyazo
set -e

# source debconf stuff
. /usr/share/debconf/confmodule

dbc_first_version=1.0.0
dbc_dbuser=pyazo
dbc_dbname=pyazo

# source dbconfig-common shell library, and call the hook function
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/config.mysql
    dbc_go pyazo "$@"
fi

#DEBHELPER#

exit 0
