#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go pyazo "$@"
fi


if [ "$1" = "purge" ]; then
        if which ucf >/dev/null 2>&1; then
                ucf --purge /etc/pyazo/database-config
                ucfr --purge pyazo /etc/pyazo/database-config
	fi
        rm -rf /etc/pyazo/
fi

#DEBHELPER#

