#!/bin/bash

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql

# you can set the default database encoding to something else
dbc_mysql_createdb_encoding="UTF8"
dbc_generate_include=template:/etc/pyazo/config.d/database.yml
dbc_generate_include_args="-o template_infile=/usr/share/pyazo/database.yml"
dbc_go pyazo "$@"

if [ -z "`getent group pyazo`" ]; then
  addgroup --quiet --system pyazo
fi
if [ -z "`getent passwd pyazo`" ]; then
  echo " * Creating user and group pyazo..."
  adduser --quiet --system --home /usr/share/pyazo --shell /bin/false --ingroup pyazo --disabled-password --disabled-login --gecos "pyazo User" pyazo
fi
chown -R pyazo: /var/log/pyazo/
chown -R pyazo: /usr/share/pyazo/
chown -R pyazo: /etc/pyazo/
if [ ! -f '/etc/pyazo/secret_key' ]; then
  echo " * Generating Secret Key"
  /usr/share/pyazo/pyazo.sh generate_secret_key > /etc/pyazo/secret_key 2> /dev/null
fi
chmod 440 /etc/pyazo/secret_key
echo " * Running Database Migration"
/usr/share/pyazo/pyazo.sh migrate
echo " * A superuser can be created with this command '/usr/share/pyazo/pyazo.sh createsuperuser'"
echo " * You should probably also adjust your settings in '/etc/pyazo/config.yml'"

#DEBHELPER#
