"""
Django settings for pyazo project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import logging
import os
import socket
import sys
from urllib.parse import urlparse

from pyazo import __version__
from pyazo.utils.config import CONFIG

LOGGER = logging.getLogger(__name__)



SECURE_PROXY_SSL_HEADER = tuple(CONFIG.get('secure_proxy_header', {}).items())[0]

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONFIG.get('secret_key',
                        '48e9z8tw=_z0e#m*x70&)u%cgo8#=16uzdze&i8q=*#**)@cp&')  # noqa Debug

DEBUG = CONFIG.get('debug')
CORS_ORIGIN_ALLOW_ALL = DEBUG

# config's external_url is a full URL, so we have to parse it to get the host
# Also allow server's hostname and server's fqdn
ALLOWED_HOSTS = set([
    urlparse(CONFIG.get('external_url')).netloc,
    socket.getfqdn(),
    socket.gethostname()
])

LOGIN_REDIRECT_URL = 'index'
# Application definition
LOGIN_URL = 'accounts-login'
LOGOUT_REDIRECT_URL = 'accounts-login'
INTERNAL_IPS = ['127.0.0.1']

# Redis settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://%s" % CONFIG.get('redis'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
DJANGO_REDIS_IGNORE_EXCEPTIONS = True
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True
SESSION_CACHE_ALIAS = "default"

# Celery settings
# Add a 10 minute timeout to all Celery tasks.
CELERY_TASK_SOFT_TIME_LIMIT = 600
CELERY_BEAT_SCHEDULE = {}
CELERY_CREATE_MISSING_QUEUES = True
CELERY_TASK_DEFAULT_QUEUE = 'pyazo'
CELERY_BROKER_URL = 'redis://%s' % CONFIG.get('redis')
CELERY_RESULT_BACKEND = 'redis://%s' % CONFIG.get('redis')
CELERY_IMPORTS = ('pyazo.core.tasks', )

# Influxdb settings
# with CONFIG.cd('influx'):
#     INFLUXDB_DISABLED = not CONFIG.get('enabled')
#     INFLUXDB_HOST = CONFIG.get('host')
#     INFLUXDB_PORT = CONFIG.get('port')
#     INFLUXDB_USER = CONFIG.get('user')
#     INFLUXDB_PASSWORD = CONFIG.get('password')
#     INFLUXDB_DATABASE = CONFIG.get('database')
#     INFLUXDB_TIMEOUT = 5
#     INFLUXDB_USE_CELERY = True

ACCOUNT_EMAIL_VERIFICATION = 'none'

with CONFIG.cd('web'):
    CHERRYPY_SERVER = {
        'server.socket_host': CONFIG.get('listen', '0.0.0.0'),  # nosec
        'server.socket_port': CONFIG.get('port', 8000),
        'server.thread_pool': CONFIG.get('threads', 30),
        'log.screen': False,
        'log.access_file': '',
        'log.error_file': '',
    }

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth_passbook',
    'pyazo.core.apps.PyazoCoreConfig',
    'pyazo.api.apps.PyazoAPIConfig',
    'raven.contrib.django.raven_compat',
    'rest_framework',
    'rest_framework_swagger',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'django_auth_ldap.backend.LDAPBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'raven.contrib.django.raven_compat.middleware.SentryResponseErrorIdMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'pyazo.core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'pyazo/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

VERSION = __version__

WSGI_APPLICATION = 'pyazo.core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {}
for db_alias, db_config in CONFIG.get('databases').items():
    DATABASES[db_alias] = {
        'ENGINE': db_config.get('engine'),
        'HOST': db_config.get('host'),
        'NAME': db_config.get('name'),
        'USER': db_config.get('user'),
        'PASSWORD': db_config.get('password'),
        'OPTIONS': db_config.get('options', {}),
    }

with CONFIG.cd('email'):
    EMAIL_HOST = CONFIG.get('host', default='localhost')
    EMAIL_PORT = CONFIG.get('port', default=25)
    EMAIL_HOST_USER = CONFIG.get('user', default='')
    EMAIL_HOST_PASSWORD = CONFIG.get('password', default='')
    EMAIL_USE_TLS = CONFIG.get('use_tls', default=False)
    EMAIL_USE_SSL = CONFIG.get('use_ssl', default=False)
    EMAIL_FROM = CONFIG.get('from')
    SERVER_EMAIL = CONFIG.get('from')

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

RAVEN_CONFIG = {
    'dsn': 'https://dfcc6acbd9c543ea8d4c9dbf4ac9a8c0:5340ca78902841b5b'
           '3372ecce5d548a5@sentry.services.beryju.org/4',
    'release': VERSION,
    'environment': 'production' if DEBUG is False else 'development',
    'tags': {'site': CONFIG.get('external_url')}
}

ERROR_REPORT_ENABLED = CONFIG.get('error_report_enabled', False)
if not ERROR_REPORT_ENABLED:
    RAVEN_CONFIG['dsn'] = ''

with CONFIG.cd('log'):
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,
        'formatters': {
            'default': {
                'format': ('%(asctime)s %(levelname)-8s %(name)-55s '
                           '%(funcName)-20s %(message)s'),
            },
        },
        'handlers': {
            'console': {
                'level': CONFIG.get('level').get('console'),
                'class': 'logging.StreamHandler',
                'formatter': 'default',
            },
            'mail_admins': {
                'level': 'ERROR',
                'class': 'django.utils.log.AdminEmailHandler',
            },
            'file': {
                'level': CONFIG.get('level').get('file'),
                'class': 'logging.FileHandler',
                'formatter': 'default',
                'filename': CONFIG.get('file'),
            },
        },
        'loggers': {
            'pyazo': {
                'handlers': ['console', 'file'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'allauth': {
                'handlers': ['console', 'file'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'cherrypy': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': True,
            },
            'django': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': True,
            },
            'celery': {
                'handlers': ['console', 'file'],
                'level': 'WARNING',
                'propagate': True,
            },
        }
    }


TEST = any('test' in arg for arg in sys.argv)
TEST_RUNNER = 'xmlrunner.extra.djangotestrunner.XMLTestRunner'
TEST_OUTPUT_VERBOSE = 2

TEST_OUTPUT_FILE_NAME = 'unittest.xml'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
THUMBNAIL_ROOT = os.path.join(BASE_DIR, 'media/thumbnail/')

if TEST:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,
    }
    CELERY_TASK_ALWAYS_EAGER = True
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media_test/')
    THUMBNAIL_ROOT = os.path.join(BASE_DIR, 'media_test/thumbnail/')

os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(THUMBNAIL_ROOT, exist_ok=True)

if DEBUG is True:
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
