# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyazo', '0003_auto_20170928_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
