# Generated by Django 2.1.2 on 2018-10-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyazo', '0009_remove_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=512, upload_to='thumbnail/'),
        ),
    ]
