# Generated by Django 2.1.3 on 2018-11-17 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyazo', '0011_auto_20181011_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadview',
            name='viewee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
